---
repos:
  # Common hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      # Git
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-vcs-permalinks

      # Common errors
      - id: check-ast
      - id: check-builtin-literals
      - id: check-docstring-first
      - id: check-yaml
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: trailing-whitespace
        args: ["--markdown-linebreak-ext=md,markdown"]

      # Cross platform
      - id: check-case-conflict
      - id: mixed-line-ending
        args: [--fix=lf]

  # Shell scripts
  - repo: https://github.com/jumanjihouse/pre-commit-hooks
    rev: 3.0.0
    hooks:
      - id: shellcheck
      # - id: shfmt

  # Markdown tools
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.41.0
    hooks:
      - id: markdownlint-fix
        args: ["--disable", "MD013"]
